### ISSUE TITLE
Add documentation for compiling and programming 

### ISSUE THREAD

**Issue by wsuchy** [necroware/mce-adapter#2]
It would be useful to have the README file include at least the name of the basic tool chain and programmer
for the GAL chip.

**Comment by necroware** [comment]
The name of the tool is included in the readme already, its EQN2JED. It's a tool, which you usually have to pay for, but ask google and may be it will tell you how to work around this problem ;) I wrote my own compiler for for the GAL, but it still doesn't support some features and is not yet well tested. May be one day I'll find the time to get it in shape and open source it. As for the programmer, there are hundreds of devices. I'm using TL866II+, but you are not limited by that. Just use whatever you have.

**Comment by necroware** [comment]
Oh, almost forgot it, if you don't know how to compile the code, just use the compiled file from the release. You don't have to mess around with EQN2JED, if you don't want to change anything.

**Comment by wsuchy** [comment]
Great, thank you for clarifying! BTW You could do a series about GALs on YouTube as I couldn't find any decent tutorial for beginners. I think that FPGAs have replaced them in the modern world.

**Comment by necroware** [comment]
Yes GALs were replaced by FPGAs in most cases. But you still need GALs, if you work with retro hardware, that's why I was tinkering a lot with them. Yes, may be I'll do a special on GALs one day....
