### ISSUE TITLE
GPL License Violation?

### ISSUE THREAD

**Issue by ca0abinary** [necroware/mce-adapter#4]
It looks like a company going by gglabs is building and distributing a slightly modified version of this adapter without following the GPL 3.0 conditions. I've contacted gglabs regarding this but wanted to make the community aware as well.

- [gglabs product page](https://gglabs.us/node/2284)
- [gglabs eBay listing](https://www.ebay.com/itm/401220864442)

**Comment by necroware** [comment]
Seems like their adapter has been created even before I did this one. I didn't look into details, but it seems to be slightly different at the first glance. Did they open source the schematics? Anyway, this can't be a violation, so this can be closed.
