### ISSUE TITLE
1N5819 VIA's are not large enough. VGA Connector row spacing incorrect, Cap Incorrect

### ISSUE THREAD

**Issue by oXL0C0Xo** [necroware/mce-adapter#5]
Couple issues that I noticed while trying to build this.

The VIA's for the 1N5819 are too small, they should be the same size as the hole for the pin header or socket. I have ordered 2 different 1N5819 and both of them have thicker leads than a 1/4w resistor

The footprint for the VGA connector is incorrect, the rows of 5 are too close together, unless you are using some type of uncommon connector that I cant find.

The capacitor that you have listed in the BOM is 10x13 with 5mm lead spacing. The footprint on the PCB is 5mm diameter with a 2.5mm lead spacing

Appreciate your work on this project! Thanks again!

**Comment by 19MiRa90** [comment]
My 1N5819 fits.
There are 2 different D-SUB HD Socket. If you have not the smaller one you can push the outer pins 1-2mm to the inner
Use any very small one, 10-100µF is ok.

**Comment by oXL0C0Xo** [comment]
I didn't need help with hacks to make it work, I was just pointing out the issues I encountered in case someone capable of fixing the issues wants to do it for the next guy before they order the incorrect parts. Regardless if there are other parts that work, the part numbers in the BOM are incorrect.

**Comment by SteveGuidi** [comment]
> Regardless if there are other parts that work, the part numbers in the BOM are incorrect.

Just came across this post before ordering components -- has the BOM has been updated with parts that fit the footprints on the PCB?

**Comment by SteveGuidi** [comment]
I redrew the PCB in EasyEDA and corrected the footprints noted in this thread; see link to project below.  I also replaced the mini-USB connector with a similar-sized micro-usb for personal preference.

Sorry, I'm not familiar with the KiCad stack and there were several non-trivial updates needed for the project to work with the current version.  

https://oshwlab.com/sguidi/mce-adapter

**Comment by necroware** [comment]
I took the default VGA port footprint from KiCad and it seems to be slightly off indeed. Nothing critical, but a little bit fiddly when inserting the port indeed. I slightly readjusted the footprint on the next revision.
